name: Release

on:
  release:
    types:
      - released

jobs:
  build_release:
    name: Build frontend release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸ›ï¸ Checkout the repo
        uses: actions/checkout@v3.0.2
        with:
          path: "ha-bambulab-cards"

      - name: ğŸ“– Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: ğŸ’¿ Install Node dependencies
        working-directory: "ha-bambulab-cards"
        run: |
          ls -la
          npm ci

      - name: ğŸ§µ Build Frontned
        working-directory: "ha-bambulab-cards"
        run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          files: ha-bambulab-cards/dist/*.js

      - name: ğŸ›ï¸ Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: "greghesp/ha-bambulab"
          path: "ha-bambulab"
          token: ${{ secrets.PR_TOKEN }}

      - name: ğŸ“ Copy file to target repo
        run: |
          ls -la
          cp ha-bambulab-cards/dist/* ha-bambulab/custom_components/bambu_lab/frontend/*

      - name: ğŸ”„ Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PR_TOKEN }}
          commit-message: "chore: Update Frontend from latest release"
          title: "chore: Update Frontend from latest release ${{ github.event.release.tag_name }}"
          body: |
            Automated PR to update frontend from latest release
            Release: ${{ github.event.release.tag_name }}
          branch: update-frontend-from-release
          base: main
          path: ha-bambulab
